# Generated by Django 4.2.17 on 2025-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_moderatoraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatoraction',
            name='post',
            field=models.UUIDField(),
        ),
    ]
