# Generated by Django 4.2.17 on 2025-01-16 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0005_alter_moderatoraction_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatoraction',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='target_moderatoraction_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moderatoraction',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderator_moderatoraction_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
