# Generated by Django 4.2.17 on 2025-01-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0006_moderatoraction_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deletion', 'Deletion')], max_length=20)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('moderative', 'Moderative')], max_length=20)),
                ('post', models.UUIDField()),
                ('action_performed_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_action_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_action_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeratorAction',
        ),
    ]
