# Generated by Django 4.2.17 on 2025-01-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
